# ==========================================
#         RTPZONE CONFIGURATION
# ==========================================

rtp:
  # Rastgele isinlanma mesafeleri
  max-radius: 10000
  min-radius: 1000
  # Her oyuncu icin geri sayim suresi (saniye)
  countdown: 30
  # Isinlanma yapilacak dunya (bos birakirsaniz mevcut dunyaya isinlanir)
  target-world: "world"

messages:
  prefix: "&8[&b&lʀᴛᴘ&f&lᴢᴏɴᴇ&8] &7"
  wand-received: "&aꜱᴇᴄɪᴍ ʙᴀʟᴛᴀꜱɪɴɪ ᴀʟᴅɪɴɪᴢ. ꜱᴏʟ ᴠᴇ ꜱᴀɢ ᴛɪᴋ ɪʟᴇ ʙᴏʟɢᴇ ꜱᴇᴄɪɴ."
  pos1-set: "&a1. ᴘᴏᴢɪꜱʏᴏɴ ꜱᴇᴄɪʟᴅɪ."
  pos2-set: "&a2. ᴘᴏᴢɪꜱʏᴏɴ ꜱᴇᴄɪʟᴅɪ."
  zone-created: "&aʙᴏʟɢᴇ ʙᴀꜱᴀʀɪʏʟᴀ ᴏʟᴜꜱᴛᴜʀᴜʟᴅᴜ: &e%name%"
  entered-zone: "&cʀᴛᴘ ʙᴏʟɢᴇꜱɪɴᴇ ɢɪʀᴅɪɴɪᴢ! ɪꜱɪɴʟᴀɴᴍᴀ ʙᴇᴋʟᴇɴɪʏᴏʀ..."
  left-zone: "&cʙᴏʟɢᴇᴅᴇɴ ᴄɪᴋᴛɪɢɪɴɪᴢ ɪᴄɪɴ ɪꜱɪɴʟᴀɴᴍᴀ ɪᴘᴛᴀʟ ᴇᴅɪʟᴅɪ."
  teleporting: "&aʀᴀꜱɢᴇʟᴇ ʙɪʀ ʙᴏʟɢᴇʏᴇ ɪꜱɪɴʟᴀɴᴅɪɴɪᴢ!"
  select-first: "&cᴏɴᴄᴇ ʙᴀʟᴛᴀ ɪʟᴇ ɪᴋɪ ɴᴏᴋᴛᴀ ꜱᴇᴄᴍᴇʟɪꜱɪɴɪᴢ."
  usage: "&cᴋᴜʟʟᴀɴɪᴍ: /ʀᴛᴘᴢᴏɴᴇ <ᴡᴀɴᴅ|ᴄʀᴇᴀᴛᴇ|ᴅᴇʟᴇᴛᴇ|ʀᴇꜱᴇᴛ|ʀᴇʟᴏᴀᴅ>"
  
  # Ekranda gorunecek geri sayim yazilari
  countdown-title: "&6&l%time%"
  countdown-subtitle: "&e&nꜱᴀɴɪʏᴇ ꜱᴏɴʀᴀ ɪꜱɪɴʟᴀɴᴀᴄᴀᴋꜱɪɴɪᴢ"

# Olusturulan bolgeler otomatik olarak buraya kaydedilir.
# El ile mudahale etmenize gerek yoktur.
zones: {}